config/routes.rb
Redactify::Application.routes.draw do

  resources :users, :only => [:show, :update] do
    resources :spoilers
  end
  
  get "/mentions" => "users#show", :section => "mentions", :as => "mentions"
  get "/retweeted_by_me" => "users#show", :section => "retweeted_by_me", :as => "retweeted_by_me"
  get "/retweets_of_me" => "users#show", :section => "retweets_of_me", :as => "retweets_of_me"
  
  resources :tweets, :only => [:show]

  resource :retweet, :only => [:create]
  resource :timeline, :only => [:show, :update, :create]
  resources :lists, :only => [:show, :update]
  resources :searches, :only => [:index, :create]
  resource :trends, :only => [:show, :update]
  resource :rate_limit, :only => [:update]
  
  get "/about" => 'static#about', :as => "about"

  root :to => "static#index"

end

app/models/tweet.rb
require "cgi"

class Tweet
  extend ActiveModel::Naming
  
  attr_reader :tweet
    
  def initialize(tweet, type = :normal)
    @tweet = tweet
    @type = type
    @css_classes = ["tweet"]
  end
  
  def search?
    @type == :search
  end
  
  def id
    # return @tweet["from_user_id"] if search?
    @tweet["id"]
  end
  
  def text
    @tweet["text"]
  end
  
  def screen_name
    return @tweet["from_user"] if search?
    @tweet["user"]["screen_name"]
  end
  
  def profile_image_url
    return @tweet["profile_image_url"] if search?
    @tweet["user"]["profile_image_url"]
  end
  
  def protected?
    return false if search?
    @tweet["user"]["protected"]
  end
  
  def created_at
    Time.parse(@tweet["created_at"]).strftime("%a, %b %d, %Y %I:%M%p")
  end
  
  def source
    return CGI.unescapeHTML(@tweet["source"]) if search?
    @tweet["source"]
  end
  
  def in_reply_to_screen_name
    return @tweet["to_user_id"] if search?
    @tweet["in_reply_to_screen_name"]
  end
  
  def in_reply_to_status_id
    @tweet["in_reply_to_status_id"]
  end
  
  def add_css_classes(classes)
    @css_classes ||= ""
    @css_classes << " #{classes}"
  end
  
  def css_classes
    return @css_classes if @css_classes.is_a? String
    @css_classes.join(" ")
  end
  
  def css_classes=(val)
    @css_classes = val
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def show
    @user = current_user
    @tweet = @user.get_tweet(params[:id])
    respond_to do |format|
      format.js { render :partial => @tweet }
    end
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
  
  def tweet_output(tweet)
    auto_link(auto_link_twitter(tweet), :link => :urls, :html => { :target => '_blank'} )
  end
  
end

app/views/tweets/_tweet.html.erb
<div id="tweet_<%= tweet.id %>" class="<%= tweet.css_classes %>" data-tweet="<%= tweet.id %>" data-screen_name="<%= tweet.screen_name %>">
  <span class="user_info">
    <%= link_to image_tag(tweet.profile_image_url, :size => "50x50"), "http://twitter.com/#{tweet.screen_name}", :target => "_blank" %>
  </span> 
  <span class="tweet_text">
    <%= image_tag("lock.png") if tweet.protected? %>
    <%= link_to tweet.screen_name, user_path(:id => tweet.screen_name) %>
    <%= tweet_output(tweet.text) %>
    <br />
    <small>
      <%= link_to(tweet.created_at, "http://twitter.com/#{tweet.screen_name}/status/#{tweet.id}", :target => "_blank") %>
      <%= "using #{tweet.source}".html_safe %>
      <%= link_to("in reply to #{tweet.in_reply_to_screen_name}", "http://twitter.com/#{tweet.in_reply_to_screen_name}/status/#{tweet.in_reply_to_status_id}", :target => "_blank") unless tweet.in_reply_to_status_id.nil? %>
      <%- if tweet.tweet["retweeted_by"] %>
        <br />
        Retweeted by:
        <%= retweeted_by_links(tweet) %>
      <% end %>
    </small>
        
    <div class="hidden_controls" style="display: none;">
      <%- unless tweet.screen_name == @user.login %>
        <%= link_to "retweet", retweet_path(:tweet_id => tweet.id), :method => :post %>
        <%= link_to "reply", "#reply", :remote => true, :class => "reply" %>
      <% end %>
    </div>
  </span>
</div>