config/routes.rb
Redactify::Application.routes.draw do

  resources :users, :only => [:show, :update] do
    resources :spoilers
  end
  
  get "/mentions" => "users#show", :section => "mentions", :as => "mentions"
  get "/retweeted_by_me" => "users#show", :section => "retweeted_by_me", :as => "retweeted_by_me"
  get "/retweets_of_me" => "users#show", :section => "retweets_of_me", :as => "retweets_of_me"
  
  resources :tweets, :only => [:show]

  resource :retweet, :only => [:create]
  resource :timeline, :only => [:show, :update, :create]
  resources :lists, :only => [:show, :update]
  resources :searches, :only => [:index, :create]
  resource :trends, :only => [:show, :update]
  resource :rate_limit, :only => [:update]
  
  get "/about" => 'static#about', :as => "about"

  root :to => "static#index"

end

app/models/user.rb
require "yaml"
require "cgi"
require "open-uri"

class User < TwitterAuth::GenericUser

  has_many :spoilers

  def assign_tweets(tweets, type)
    tweets.map do |tweet|
      if spoiler?(tweet["text"])
        Redacted.new(tweet,spoiled_on(tweet["text"]), type)
      elsif tweet["retweeted_status"]
        Retweet.new(tweet, type)
      else
        Tweet.new(tweet, type)
      end
    end
  end

  def spoiler_free_timeline(options = {})
    
    if options[:search]
      tweets = search(options)["results"]
      type = :search
    else
      tweets = timeline(options)
      type = :normal
    end
            
    assign_tweets(tweets, type)
  end
  
  def get_retweeted_by(tweet)
    twitter.get("http://api.twitter.com/1/statuses/#{tweet["id"]}/retweeted_by.json")
  end
  
  def get_lists
    begin
      twitter.get("http://api.twitter.com/1/#{login}/lists.json")["lists"]
    rescue
      # return File.open("#{Rails.root}/db/test_lists.yml") { |file| YAML.load(file) } if Rails.env == "development"
      return []
    end
  end
  
  def get_tweet(id)
    tweet = twitter.get("/statuses/show/#{id}.json")
    if tweet["retweeted_status"]
      Retweet.new(tweet)
    else
      Tweet.new(tweet)
    end
  end
  
  def trends
    url = "http://search.twitter.com/trends.json"
    puts "TWITTER: Getting URL: #{url}" if Rails.env == "development"
    twitter.get(url)["trends"]
    # return []
  end
  
  def rate_limit_status
    begin
      twitter.get("http://twitter.com/account/rate_limit_status.json")
    rescue
      {}
    end
  end
  
  def spoiler?(tweet)
    return spoilers.any? {|spoiler| tweet =~ Regexp.new(Regexp.escape(spoiler.name), Regexp::IGNORECASE)}
  end
  
  def spoiled_on(tweet)
    spoilers.reject {|spoiler| tweet !~ Regexp.new(Regexp.escape(spoiler.name), Regexp::IGNORECASE)}
  end
  
  def popular_tags
    my_spoilers = spoilers.collect(&:name)
    conditions = []
    conditions = ["name NOT IN (?)", my_spoilers] unless my_spoilers.empty?
    cols = Spoiler.column_names.collect {|c| "spoilers.#{c}"}.join(",")
    
    Spoiler.find(:all, 
      :select => "#{cols},count(*) as count", 
      :conditions => conditions, 
      :order => "count DESC",
      :limit => 5,
      :group => "name, #{cols}")
  end
  
  def post_tweet(tweet)
    if tweet.length <= 140
      twitter.post('/statuses/update.json', 'status' => tweet["status"], 'in_reply_to_status_id' => tweet["in_reply_to_status_id"]) 
    else
      errors.add("tweet", "Status update over 140 characters")
    end
  end
  
  def retweet(tweet_id)
    url = "http://api.twitter.com/1/statuses/retweet/%s.json"
    twitter.post(url % tweet_id)
  end
  
  private
  
  def search(options)
    options = HashWithIndifferentAccess.new(options)
    
    url = "http://search.twitter.com/search.json?rpp=50&q=#{CGI.escape(options[:q])}"
    # url << "?#{options.to_query}" unless options.empty?
    
    puts "TWITTER: Getting URL: #{url}" if Rails.env == "development"
    twitter.get(url)
  end
  
  def timeline(options)
    
    options = HashWithIndifferentAccess.new(options)
    
    url = case
      when options["list_id"] 
        "http://api.twitter.com/1/#{login}/lists/#{options["list_id"]}/statuses.json"
      when options["screen_name"] 
        "/statuses/user_timeline/#{options["screen_name"]}.json"
      when options[:section] == "mentions"
        "http://api.twitter.com/1/statuses/mentions.json"
      when options[:section] == "retweeted_by_me"
        "http://api.twitter.com/1/statuses/retweeted_by_me.json"
      when options[:section] == "retweets_of_me"
        "http://api.twitter.com/1/statuses/retweets_of_me.json"
      else 
        "/statuses/home_timeline.json"
    end
    
    url << "?#{options.to_query}" unless options.empty?
    
    puts "TWITTER: Getting URL: #{url}" if Rails.env == "development"
     
    ## Test from local files    
    # tweets = File.open("#{Rails.root}/db/test_tweets.yml") { |file| YAML.load(file) }
    # tweets.first["text"] = url
    # return tweets          
    
    ## Get data from twitter
    twitter.get(url)

  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :check_login
  before_filter :load_user
  # before_filter :set_urls, :only => [:show]
  before_filter :load_trends, :only => [:show]
  after_filter :update_latest_tweet, :only => [:show]
  
  def show   
    @page = params[:page] ||= 1
     
    case params[:section]
      when "mentions"
        get_timeline("mentions", :section => "mentions")
      when "retweeted_by_me"
        get_timeline("retweeted_by_me", :section => "retweeted_by_me")
      when "retweets_of_me"
        get_timeline("retweets_of_me", :section => "retweets_of_me")
        @timeline.map {|t| t.tweet["retweeted_by"] = @user.get_retweeted_by(t.tweet) }
      else
        @get_more_url = user_path(:id => params[:id], :page => @page.to_i + 1)
        @update_tweets_url = user_path(:id => params[:id])
        @timeline = @user.spoiler_free_timeline(:screen_name => params[:id], :page => @page)
    end
    
    respond_to do |format|
      format.html { render "timelines/show" }
      format.js { render :partial => "timelines/tweets", :locals => { :tweets => @timeline } }
    end
  end
  
  ## FIXME
  def update
    @new_tweets = @user.spoiler_free_timeline(:screen_name => params[:id], :since_id => session[:latest_id])
    load_new_tweets(@new_tweets)
  end
  
  private
  
  def get_timeline(section, options = {})
    path = "#{section}_path"
    @get_more_url = self.send(path, options.merge(:page => @page.to_i + 1))
    @update_tweets_url = self.send(path)
    @timeline = @user.spoiler_free_timeline(:page => @page, :section => section)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bar.html.erb
<%- if logged_in? %>
  <%= image_tag(current_user.profile_image_url, :width => 24, :height => 24) %>
  <strong><%= link_to "@#{current_user.login}", user_path(:id => current_user.login) %></strong>
  <br />
  <div id="user_actions">
    <small>
      <%= link_to "timeline", timeline_path %>
      <%= link_to "mentions", mentions_path %>
      <%= link_to "retweets by me", retweeted_by_me_path %>
      <%= link_to "retweets of me", retweets_of_me_path %>
      <%= link_to 'sign out', logout_path %>
    </small>
  </div>
<%- else %>
  <%= link_to 'Login via Twitter', '/login' %>
<% end %>

app/views/users/_rate_limit.html.erb
Twitter API Calls Remaining: 
<%= "#{rate_limit["remaining_hits"]}/#{rate_limit["hourly_limit"]}" %>
<br />
<%= "Resets: #{rate_limit["reset_time"]}" %>

<%= javascript_tag "if (#{rate_limit["remaining_hits"]} < 15) { alert('You are running out of api calls. Twitter only allows #{rate_limit["hourly_limit"]} per hour.')}" %>

app/views/users/_trends.html.erb
<h3>
  Trends
  <%= link_to "update", trends_path, :remote => true, :method => :put, :id => "update_trends" %>
</h3>

<ul>
  <% for trend in @trends %>
    <li><%= link_to("#{trend["name"]}", searches_path(:q => trend["name"]), :method => :post) %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
	<div id="side">
	  <div id="spoiler_tags" class="side_content">
      <%= render "form", :user => @user %>
	
  		<h3>Your Spoiler Tags</h3>
  
  	  <% for spoiler in @user.spoilers %>
  	    <%= spoiler.name %>
  	    <small><%= link_to "remove", [@user,spoiler], :method => :delete, :confirm => "really delete \"#{spoiler.name}\"?" %></small>
  	    <br />
  	  <% end %>
	  </div>

		<div id="popular_spoilers" class="side_content">
			<%= render "spoilers/popular"%>
		</div>
		
		<div id="rate_limit" class="side_content">
		  Twitter API Calls Remaining: <%= "#{@rate_limit["remaining_hits"]}/#{@rate_limit["hourly_limit"]}" %><br />
		  Resets: <%= @rate_limit["reset_time"] %>
		</div>
	</div>

	<div id="timeline">
	  <h2>Timeline</h2>
	  <% for tweet in @user.spoiler_free_timeline %>
      <%= render tweet %>
	  <% end %>
	</div>