config/routes.rb
Redactify::Application.routes.draw do

  resources :users, :only => [:show, :update] do
    resources :spoilers
  end
  
  get "/mentions" => "users#show", :section => "mentions", :as => "mentions"
  get "/retweeted_by_me" => "users#show", :section => "retweeted_by_me", :as => "retweeted_by_me"
  get "/retweets_of_me" => "users#show", :section => "retweets_of_me", :as => "retweets_of_me"
  
  resources :tweets, :only => [:show]

  resource :retweet, :only => [:create]
  resource :timeline, :only => [:show, :update, :create]
  resources :lists, :only => [:show, :update]
  resources :searches, :only => [:index, :create]
  resource :trends, :only => [:show, :update]
  resource :rate_limit, :only => [:update]
  
  get "/about" => 'static#about', :as => "about"

  root :to => "static#index"

end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController
  before_filter :check_login
  before_filter :load_user
  
  def index
    @page = params[:twitter][:page].to_i + 1 if params[:twitter] && params[:twitter][:page]
    @timeline = @user.spoiler_free_timeline(params[:twitter] || {})
    session[:latest_id] = @timeline.first.id unless params[:twitter] && params[:twitter][:page]
    respond_to do |format|
      format.html
      format.js
      format.json { render :json => @timeline.to_json }
    end
  end

  def create
    @user.post_tweet(params[:tweet])
    if @user.errors.empty?
      flash[:notice] = "New Tweet Posted"
    else
      flash[:error] = "There was a problem posting the twitter update: #{current_user.errors[:tweet]}"
    end
    redirect_to timeline_path
  end
  
  def new
    @new_tweets = @user.spoiler_free_timeline(params[:twitter].merge("since_id" => session[:latest_id]))
    
    if @new_tweets.empty?
      render :update do |page|
        page << update_rate_limit
      end
    else
      session[:latest_id] = @new_tweets.first.id
      render :format => :js
    end
  end
  
  private
  
  def load_user
    @user = current_user
    
  end
  
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  before_filter :check_login
  before_filter :load_user
  before_filter :load_trends, :only => [:show]
  after_filter :update_latest_tweet, :only => :show
  
  def show
    @page = params[:page] ||= 1
    @get_more_url = timeline_path(:page => @page.to_i + 1)
    @update_tweets_url = timeline_path
    @timeline = @user.spoiler_free_timeline(:page => @page)
    respond_to do |format|
      format.html
      format.js { render :partial => "timelines/tweets" }
      format.json { render :json => @timeline.to_json }
    end
  end

  def create
    @user.post_tweet(params[:tweet])
    if @user.errors.empty?
      flash[:notice] = "New Tweet Posted"
    else
      flash[:error] = "There was a problem posting the twitter update: #{current_user.errors[:tweet]}"
    end
    redirect_to timeline_path
  end
  
  def update
    @new_tweets = @user.spoiler_free_timeline(:since_id => session[:latest_id])
    @new_tweets.map {|tweet| tweet.add_css_classes "new"}

    respond_to do |format|
      format.js do
        session[:latest_id] = @new_tweets.first.id unless @new_tweets.empty?
        render :partial => @new_tweets, :locals => {:css_classes => "new"}
      end
    end
  end

end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/views/timeline/index.html.erb
<table>
	<tbody>
		<tr>
			<td id="timeline">
					<%= render "timeline/post_tweet" %>
					<div id="updated_tweets"></div>
				  <%= render "timeline/tweets" %>
					<%= periodically_call_remote(:url => new_timeline_path(:twitter => params[:twitter]), :frequency => '90', :method => :get) %>
			</td>

			<td id="side">
					<div class="side_content">
						<h3>Add New Spoiler Tag</h3>
			    	<%= render "timeline/form", :user => @user %>
					</div>

					<div id="lists" class="side_content">
						<h3>Lists</h3>
						<ul>
							<li><%= link_to "@#{current_user.login}", timeline_path %></li>
							<% for list in @user.get_lists["lists"] %>
								<li><%= link_to list["full_name"], list_path(list["id"]) %></li>
							<% end %>
						</ul>
					</div>

				  <div id="spoiler_tags" class="side_content">
	
			  		<h3>Your Spoiler Tags</h3>
						<%= render "spoilers/user", :user => @user %>
				  </div>

					<div id="popular_spoilers" class="side_content">
						<h3>Popular Tags</h3>
						<%= render "spoilers/popular", :user => @user %>
					</div>
		
					<div id="rate_limit" class="side_content">
						<%= render "users/rate_limit", :rate_limit => @user.rate_limit_status %>
					</div>
			</td>
		</tr>
			
	</tbody>
</table>