config/routes.rb
Redactify::Application.routes.draw do

  resources :users, :only => [:show, :update] do
    resources :spoilers
  end
  
  get "/mentions" => "users#show", :section => "mentions", :as => "mentions"
  get "/retweeted_by_me" => "users#show", :section => "retweeted_by_me", :as => "retweeted_by_me"
  get "/retweets_of_me" => "users#show", :section => "retweets_of_me", :as => "retweets_of_me"
  
  resources :tweets, :only => [:show]

  resource :retweet, :only => [:create]
  resource :timeline, :only => [:show, :update, :create]
  resources :lists, :only => [:show, :update]
  resources :searches, :only => [:index, :create]
  resource :trends, :only => [:show, :update]
  resource :rate_limit, :only => [:update]
  
  get "/about" => 'static#about', :as => "about"

  root :to => "static#index"

end

app/models/redacted.rb
class Redacted < Tweet
  attr_accessor :tweet, :tags
  
  def initialize(tweet,tags,type = :normal)
    @tweet = tweet
    @tags = tags
    @type = type
    @css_classes = ["tweet", "redacted"]
  end
  
end

app/views/redacteds/_redacted.html.erb
<div id="tweet_<%= redacted.id %>" class="<%= redacted.css_classes %>">
  <span class="user_info">
    <%= link_to image_tag(redacted.profile_image_url, :size => "50x50", :class => "user_image"), "http://twitter.com/#{redacted.screen_name}", :target => "_blank" %>
  </span> 

  <span class="tweet_text">
    <%= image_tag("lock.png") if redacted.protected?  %>
    <%= link_to redacted.screen_name, timeline_path(:screen_name => redacted.screen_name) %>
    <span class="redacted">REDACTED</span>
    <%= link_to "show", tweet_path(redacted.id), :method => :get, :remote => true, :class => "action show_redacted_tweet" %>
    <br />
    <small>
      <strong>matched tags:</strong>
      <%= redacted.tags.collect(&:name).join(", ") %>
    </small>
  </span>
</div>